version: '3.8'

services:
    mysql:
      image: mysql:5.7.12
      container_name: central-system-db
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_DATABASE=central-system-db
        - MYSQL_ROOT_PASSWORD=central-system-db-pwd
        - MYSQL_PASSWORD=central-system-db-pwd
      ports:
        - "3307:3306"
      expose:
        - 3307
    backend:
      container_name: central-system-api
      build:
          context: .
          dockerfile: ./Dockerfile
      depends_on:
        - mysql
      ports:
          - 3000:3000
      environment:
        DATABASE_NAME: central-system-db
        DATABASE_HOST: central-system-db
        DATABASE_PORT: 3306
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: central-system-db-pwd